server:
  port: 8991
  servlet:
    context-path: /cognizant/frank-garage

spring:
  datasource:
    url: jdbc:mariadb://mariadb-service:3306/frank_garage
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
